#
# Configuration de l'application
#
appname = beerama
title = "Beerama"
description = "Organiser vos photos en album et diaporama"
httpport = 8080

# Version de l'application
# voir dans ../CHANGELOG.md
version = "3.1.5 du 11 nov 2025"

# dev / prod pour ne pas afficher les erreurs en détail
runmode = dev

# Session
SessionOn = true
# mettre true en HTTPS
EnableXSRF = true 
XSRFExpire = 7200
# openssl rand -hex 24
XSRFKey = "6a169845bea848ca74b1b4a80e942ae8190aa9cf"

# Source
github = "https://github.com/pbillerot/beerama"
# Aide
help = "https://philippe.billerot.net/beerama-doc"

# Icones
favicon = "/static/img/bee.svg"
# Icone de l'application
icon = "/static/img/bee.svg"
# fond d'écran
background = "/static/img/bee-bg-black.jpg"

# fichier des utilisateurs 
users = "/home/billerot/tmp/beerama/.beeusers.conf"

# Répertoire des albums et thumbnails
racine = "/home/billerot/tmp/beerama/albums"
original = "/home/billerot/tmp/beerama/backup"
thumbnail = "/home/billerot/tmp/beerama/thumbs"
trash = "/home/billerot/tmp/beerama/trash"
index = "/home/billerot/tmp/beerama/index"

# Taille des vignettes
width = 400
height = 400

# Production Settings (only active when runmode = prod)
[prod]
recoverpanic = false 
# Override global setting for production stability

include "custom.conf"