# fichier exemple de droits d'accès à l'album
# à placer dans le répertoire de l'album
# doc https://toml.io/fr/v1.0.0

# éditeurs
[carom]
is_editor = true

# lecteurs
[robert]

# les autres n'auront pas d'accès