[philippe]
password = "philippe"
is_admin = true

[carom]
password = "carom"

[robert]
password = "robert"

# doc https://toml.io/fr/v1.0.0
# is_admin
#   peut créer recharger les albums
#   gère les droits d'accès pour chaque album
