#
# custom.conf - à personnaliser sur le site
#
#debug = false # pour avoir les traces des requêtes sql
EnableXSRF = false
debug = true
# runmode = "production"
# debug = false

# openssl rand -hex 24
XSRFKey = "3060f6d5ac29dec399a503b4610ea2fcd7179741398aea5e"

# fichier des utilisateurs 
users = "/home/billerot/tmp/beerama/.beeusers.conf"

# Répertoire des albums et thumbnails
racine = "/home/billerot/tmp/beerama/albums"
original = "/home/billerot/tmp/beerama/backup"
thumbnail = "/home/billerot/tmp/beerama/thumbs"
trash = "/home/billerot/tmp/beerama/trash"
index = "/home/billerot/tmp/beerama/index"

runmode = "dev"
[dev]
#user = "carom"
user = "philippe"
#group = "admin"

# Production Settings (only active when runmode = prod)
[prod]
recoverpanic = false 
# Override global setting for production stability
