# IMAGE beerama

# ETAPE COMPILATION DANS UNE IMAGE GOLANG ALPINE
# Le GOPATH par défaut de cette image est /go.
FROM golang:alpine AS goalpine

# Installation de GCC et GIT
RUN apk add build-base git

# Installation de beerama
WORKDIR /github/pbillerot
RUN git clone https://beerama.git

WORKDIR /github/pbillerot/beerama

# Compilation avec CGO AMD64 ou ARM64
RUN GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /github/pbillerot/beerama/beerama

# ETAPE GENERATION D'UNE IMAGE ALPINE
# avec seulement l'exécutable golang
FROM alpine

# Ajout de tzdata pour régler l'heure
RUN apk add tzdata
ENV TZ=Europe/Paris
RUN cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

# ajout de exiftool pour lire et modifier les metadata des images et extraire la vignette des vidéos
RUN apk add exiftool ffmpeg

# Installation de beerama...
# seuls les répertoires conf et views ne seraient nécessaires
RUN mkdir -p /github/pbillerot/beerama
COPY --from=goalpine /github/pbillerot/beerama /github/pbillerot/beerama

# Installation de python3 et de pip pour les travaux planifiés
RUN apk add --no-cache python3 py3-pip
# Vérification 
RUN python3 --version

# PLANIFICATION DES TRAVAUX
WORKDIR /app
COPY nettoyer_vieux_fichiers.py .
# le plus simple pour crontab (tlj à 7h10)
RUN echo "10 7 * * * python3 /app/nettoyer_vieux_fichiers.py" > /var/spool/cron/crontabs/root

# Le port sur lequel notre serveur écoute
EXPOSE 8080

# Point d'entrée
WORKDIR /github/pbillerot/beerama

ENTRYPOINT ["./beerama"]

# docker exec -u root -it beerama /bin/sh